#!/bin/sh

dev="eth0"
auth_port="C"
addr="192.168.17.1"
subnet="192.168.17.0/24"

ifconfig $auth_port $addr

iptables -A FORWARD -o $dev -i C -s $subnet -m conntrack --ctstate NEW -j ACCEPT
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
iptables -t nat -F POSTROUTING
iptables -t nat -A POSTROUTING -o $dev -j MASQUERADE
